import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {ArrowUp, AudioLines, Camera, Check, ChevronDown, Cpu, FileText, FolderOpen, Globe, ImagePlus, LockKeyhole, LogOut, Menu, MessageSquare, Mic, Monitor, Plus, Settings2, ShieldCheck, Sparkles, Square, Terminal, Trash2, Volume2, Wrench, X, Zap} from 'lucide-react';
import {api, csrf, setCsrf, streamChat} from './api';
import './style.css';

type Message = {id?:number; role:string;content:string;model?:string;status?:string};
type Conversation = {id:string;title:string};
type Tool = {name:string;description:string;enabled:boolean;permission:string;group:string};
type Config = {model:string;max_iterations:number;confirm_writes:boolean;tools_disabled:boolean;auto_voice:boolean;roots:string[];vision:boolean;stt:boolean;computer:{available:boolean;reason:string}};
const json = (value:unknown) => JSON.stringify(value);
const shortModel = (name:string) => name.split('/').at(-1) || name;

function Mark({small=false}:{small?:boolean}) {return <div className={'brand-mark '+(small?'small':'')}><AudioLines size={small?20:30}/></div>}
function Toggle({checked,onChange,label,disabled=false}:{checked:boolean;onChange:()=>void;label:string;disabled?:boolean}) {return <button type="button" role="switch" aria-checked={checked} aria-label={label} disabled={disabled} className={'toggle '+(checked?'on':'')} onClick={onChange}><span/></button>}

function Login({ready}:{ready:()=>void}) {
  const [setup,setSetup]=useState(false), [password,setPassword]=useState(''), [key,setKey]=useState(''), [error,setError]=useState(''), [busy,setBusy]=useState(false);
  useEffect(()=>{api('/auth/status').then(r=>setSetup(r.setup_required)).catch(e=>setError(e.message))},[]);
  async function submit(e:React.FormEvent) {e.preventDefault();setBusy(true);setError('');try {const r=await api('/auth/login',{method:'POST',body:json({password,setup_key:key})});setCsrf(r.csrf);ready()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <div className="login-layout"><div className="login-brand"><Mark/><span>NEXO <b>LOCAL</b></span></div><form className="login-card" onSubmit={submit}><div className="eyebrow"><LockKeyhole size={14}/> TU ESPACIO PRIVADO</div><h1>{setup?'Tu IA. Tu computadora.':'Volvé a tu espacio.'}</h1><p>{setup?'Creá tu contraseña para empezar. Tus conversaciones se guardan en esta computadora.':'Ingresá tu contraseña para acceder a tu asistente local.'}</p>{setup&&<label>Código de instalación<input required value={key} onChange={e=>setKey(e.target.value)} autoComplete="off" placeholder="Pegá el código de data/setup-key.txt"/><small>Lo encontrás dentro de la carpeta del proyecto. Solo se usa una vez.</small></label>}<label>Contraseña<input required type="password" minLength={12} maxLength={200} value={password} onChange={e=>setPassword(e.target.value)} autoComplete={setup?'new-password':'current-password'} placeholder="Mínimo 12 caracteres"/></label>{error&&<div className="error" role="alert">{error}</div>}<button className="primary" disabled={busy}>{busy?'Conectando…':setup?'Crear mi espacio':'Entrar a Nexo'}<ArrowUp size={17}/></button><div className="login-note"><ShieldCheck size={16}/> Sin cuenta en la nube. Sin suscripción.</div></form><p className="login-footer">Modelos locales · Herramientas con permisos · Vos tenés el control</p></div>
}

function App() {
  const [auth,setAuth]=useState<boolean|null>(null),[view,setView]=useState('chat'),[mobile,setMobile]=useState(false);
  const [conversations,setConversations]=useState<Conversation[]>([]),[cid,setCid]=useState<string|null>(null),[messages,setMessages]=useState<Message[]>([]);
  const [models,setModels]=useState<any[]>([]),[online,setOnline]=useState(false),[backend,setBackend]=useState(true),[config,setConfig]=useState<Config|null>(null),[tools,setTools]=useState<Tool[]>([]);
  const [text,setText]=useState(''),[mode,setMode]=useState('chat'),[busy,setBusy]=useState(false),[state,setState]=useState('En espera'),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [approval,setApproval]=useState<any>(null),[actions,setActions]=useState<any[]>([]),[system,setSystem]=useState<any>(null),[images,setImages]=useState<string[]>([]);
  const [memories,setMemories]=useState<any[]>([]),[memory,setMemory]=useState(''),[recording,setRecording]=useState(false),[transcribing,setTranscribing]=useState(false),[camera,setCamera]=useState<MediaStream|null>(null);
  const controller=useRef<AbortController|null>(null),bottom=useRef<HTMLDivElement>(null),input=useRef<HTMLTextAreaElement>(null),video=useRef<HTMLVideoElement>(null),recorder=useRef<MediaRecorder|null>(null),audioStream=useRef<MediaStream|null>(null),cameraRef=useRef<MediaStream|null>(null);
  const speak = (content:string) => {
    if(!('speechSynthesis' in window)){setError('Este navegador no tiene síntesis de voz.');return}
    const voices=speechSynthesis.getVoices().filter(v=>v.localService);
    const voice=voices.find(v=>v.lang.startsWith('es'));
    if(!voice){setError('No se encontró una voz local en español en este navegador.');return}
    speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(content);utterance.voice=voice;utterance.lang=voice.lang;speechSynthesis.speak(utterance);
  };
  const fail=(e:unknown)=>setError((e as Error).message);
  async function refresh() {const [c,m,s,t]=await Promise.all([api('/conversations'),api('/models'),api('/settings'),api('/tools')]);setConversations(c);setModels(m.models);setOnline(m.online);setConfig(s);setTools(t);setBackend(true)}
  useEffect(()=>{api('/auth/me').then(r=>{setCsrf(r.csrf);setAuth(true)}).catch(()=>setAuth(false));const expired=()=>setAuth(false);window.addEventListener('session-expired',expired);return()=>window.removeEventListener('session-expired',expired)},[]);
  useEffect(()=>{if(auth)refresh().catch(fail)},[auth]);
  useEffect(()=>{if(!auth)return;const tick=()=>api('/system').then(s=>{setSystem(s);setBackend(true)}).catch(()=>setBackend(false));tick();const timer=setInterval(tick,5000);return()=>clearInterval(timer)},[auth]);
  useEffect(()=>{bottom.current?.scrollIntoView({behavior:'smooth'})},[messages,actions]);
  useEffect(()=>{if(camera&&video.current){video.current.srcObject=camera;video.current.play().catch(fail)}},[camera]);
  useEffect(()=>()=>{cameraRef.current?.getTracks().forEach(t=>t.stop());audioStream.current?.getTracks().forEach(t=>t.stop());controller.current?.abort()},[]);
  async function saveConfig(patch:Partial<Config>) {if(!config)return;const updated={...config,...patch};const {model,max_iterations,confirm_writes,tools_disabled,auto_voice}=updated;const result=await api('/settings',{method:'PUT',body:json({model,max_iterations,confirm_writes,tools_disabled,auto_voice})});setConfig(result)}
  async function chooseConversation(id:string) {if(busy)return;setCid(id);setMessages(await api('/conversations/'+id+'/messages'));setActions([]);setNotice('');setView('chat');setMobile(false)}
  function newChat() {if(busy)return;setCid(null);setMessages([]);setActions([]);setImages([]);setNotice('');setError('');setView('chat');setMobile(false);input.current?.focus()}
  async function stop() {try {await api('/agent/stop',{method:'POST'});controller.current?.abort();speechSynthesis?.cancel();setApproval(null);setState('Detenido')}catch(e){fail(e)}}
  async function send(e?:React.FormEvent) {
    e?.preventDefault();if(!text.trim()||busy||!config)return;
    const content=text.trim();setError('');setNotice('');setActions([]);setBusy(true);setState('Conectando con el modelo');
    let id=cid;let answer='';
    try {
      if(!id){id=(await api('/conversations',{method:'POST'})).id;setCid(id)}
      setText('');setMessages(prev=>[...prev,{role:'user',content},{role:'assistant',content:'',model:config.model}]);
      controller.current=new AbortController();
      await streamChat({conversation_id:id,text:content,model:config.model,mode,images:images.map(x=>x.split(',')[1])},controller.current.signal,event=>{
        if(event.event==='token'){answer+=event.text;setMessages(prev=>[...prev.slice(0,-1),{role:'assistant',content:answer,model:config.model}])}
        if(event.event==='state')setState(event.text);
        if(event.event==='approval')setApproval(event);
        if(event.event==='approval_closed')setApproval(null);
        if(event.event==='tool_result')setActions(prev=>[...prev,event]);
        if(event.event==='error')setError(event.text);
        if(event.event==='notice')setNotice(event.text);
      });
      setImages([]);
      if(answer&&config.auto_voice)speak(answer);
    }catch(e){if((e as Error).name!=='AbortError'){fail(e);setText(content)}}
    finally {setBusy(false);setState('En espera');setApproval(null);controller.current=null;if(id){api<Message[]>('/conversations/'+id+'/messages').then(setMessages).catch(fail)}api<Conversation[]>('/conversations').then(setConversations).catch(fail)}
  }
  async function decide(approved:boolean) {if(!approval)return;try {await api('/approvals/'+approval.id,{method:'POST',body:json({approved})});setApproval(null)}catch(e){fail(e)}}
  async function addImage(file:File) {if(file.size>4_000_000){setError('Máximo 4 MB por imagen.');return}if(images.length>=3){setError('Máximo tres imágenes por mensaje.');return}const reader=new FileReader();reader.onload=()=>setImages(p=>[...p,reader.result as string].slice(0,3));reader.readAsDataURL(file)}
  function captureVideo(element:HTMLVideoElement) {const canvas=document.createElement('canvas');const scale=Math.min(1,1600/element.videoWidth);canvas.width=element.videoWidth*scale;canvas.height=element.videoHeight*scale;canvas.getContext('2d')!.drawImage(element,0,0,canvas.width,canvas.height);setImages(p=>[...p,canvas.toDataURL('image/jpeg',.85)].slice(0,3))}
  async function captureScreen() {let stream:MediaStream|undefined;try {stream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false});const element=document.createElement('video');element.srcObject=stream;await element.play();captureVideo(element)}catch(e){fail(e)}finally{stream?.getTracks().forEach(t=>t.stop())}}
  async function openCamera() {try {const stream=await navigator.mediaDevices.getUserMedia({video:true,audio:false});cameraRef.current=stream;setCamera(stream)}catch(e){fail(e)}}
  function closeCamera() {cameraRef.current?.getTracks().forEach(t=>t.stop());cameraRef.current=null;setCamera(null)}
  async function microphone() {
    if(recording){recorder.current?.stop();return}
    try {const stream=await navigator.mediaDevices.getUserMedia({audio:true});audioStream.current=stream;const rec=new MediaRecorder(stream);recorder.current=rec;const chunks:BlobPart[]=[];let bytes=0;
      rec.ondataavailable=e=>{bytes+=e.data.size;chunks.push(e.data);if(bytes>9_000_000&&rec.state==='recording')rec.stop()};
      rec.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());setRecording(false);setTranscribing(true);try {const form=new FormData();form.append('audio',new Blob(chunks,{type:rec.mimeType}),'voice.webm');const r=await fetch('/api/voice/transcribe',{method:'POST',headers:{'X-Local-App':'1','X-CSRF-Token':csrf},body:form});const data=await r.json();if(!r.ok)throw new Error(data.detail);setText(p=>p+' '+data.text)}catch(e){fail(e)}finally{setTranscribing(false)}};
      rec.start(1000);setRecording(true);setTimeout(()=>{if(rec.state==='recording')rec.stop()},60000);
    }catch(e){fail(e);audioStream.current?.getTracks().forEach(t=>t.stop())}
  }
  if(auth===null)return <div className="loading"><Mark/>Conectando con tu espacio…</div>;
  if(!auth)return <Login ready={()=>setAuth(true)}/>;
  const selected=models.find(m=>m.name===config?.model);
  const navigate=(v:string)=>{setView(v);setMobile(false);if(v==='settings')api('/memory').then(setMemories).catch(fail)};
  return <div className="app-shell">
    {mobile&&<div className="sidebar-shade" onClick={()=>setMobile(false)}/>}
    <aside className={'sidebar '+(mobile?'visible':'')}>
      <div className="brand"><Mark small/><span>nexo<span className="local-pill">LOCAL</span></span><button className="icon-button mobile-only" aria-label="Cerrar menú" onClick={()=>setMobile(false)}><X size={18}/></button></div>
      <button className="new-chat" disabled={busy} onClick={newChat}><Plus size={18}/>Nueva conversación<span>↗</span></button>
      <nav><button className={view==='chat'?'active':''} onClick={()=>navigate('chat')}><MessageSquare size={18}/>Conversaciones</button><button className={view==='tools'?'active':''} onClick={()=>navigate('tools')}><Wrench size={18}/>Herramientas<span className="count">{tools.filter(t=>t.enabled).length}</span></button><button className={view==='system'?'active':''} onClick={()=>navigate('system')}><Cpu size={18}/>Sistema<span className={'dot '+(backend&&online?'green':'amber')}/></button></nav>
      <div className="history-label">TU HISTORIAL<span>{conversations.length}</span></div>
      <div className="history">{conversations.length===0?<p className="history-empty">Tus conversaciones aparecerán acá.</p>:conversations.map(c=><div className={'history-row '+(cid===c.id?'selected':'')} key={c.id}><button disabled={busy} onClick={()=>chooseConversation(c.id).catch(fail)}><MessageSquare size={14}/><span>{c.title}</span></button><button disabled={busy} className="delete-chat" aria-label={'Eliminar '+c.title} onClick={()=>{if(window.confirm('¿Eliminar esta conversación?'))api('/conversations/'+c.id,{method:'DELETE'}).then(()=>{if(cid===c.id)newChat();refresh().catch(fail)}).catch(fail)}}><Trash2 size={13}/></button></div>)}</div>
      <div className="local-card"><span className={'dot '+(online?'green':'amber')}/><div><strong>{online?'Ollama conectado':'Ollama desconectado'}</strong><small>Procesamiento en tu equipo</small></div><ShieldCheck size={17}/></div>
      <button className={'settings-nav '+(view==='settings'?'active':'')} onClick={()=>navigate('settings')}><Settings2 size={18}/>Configuración</button>
      <div className="sidebar-footer"><div className="avatar">V</div><div><strong>Tu espacio</strong><small>Personal · Local</small></div><button className="icon-button" aria-label="Cerrar sesión" onClick={()=>api('/auth/logout',{method:'POST'}).then(()=>{closeCamera();audioStream.current?.getTracks().forEach(t=>t.stop());setAuth(false)}).catch(fail)}><LogOut size={17}/></button></div>
    </aside>
    <main><header className="topbar"><div className="header-left"><button className="icon-button mobile-only" aria-label="Abrir menú" onClick={()=>setMobile(true)}><Menu size={21}/></button><div className="model-picker"><Cpu size={17}/><select aria-label="Modelo de Ollama" value={config?.model||''} disabled={busy||!config} onChange={e=>saveConfig({model:e.target.value}).catch(fail)}>{!models.some(m=>m.name===config?.model)&&<option value={config?.model||''}>{config?.model||'Cargando modelos…'}</option>}{models.map(m=><option value={m.name} key={m.name}>{shortModel(m.name)}</option>)}</select><ChevronDown size={14}/></div>{selected?.capabilities?.includes('vision')&&<span className="vision-badge">Visión</span>}</div><div className="header-right"><span className="private-status"><LockKeyhole size={13}/>Privado por diseño</span><button className="stop-agent" onClick={stop}><Square size={11} fill="currentColor"/>STOP AGENT</button></div></header>
      {error&&<div className="global-error" role="alert">{error}<button aria-label="Cerrar error" onClick={()=>setError('')}><X size={16}/></button></div>}
      {view==='chat'?<section className="chat-page">
        <div className="messages-scroll">{messages.length===0?<div className="welcome"><div className="welcome-badge"><span className="dot green"/> HECHO PARA TU ESPACIO</div><Mark/><h1>¿Qué vamos a crear hoy?</h1><p>Una idea, una pregunta o el próximo paso de tu proyecto.<br/>Tu asistente está acá, en tu computadora.</p><div className="suggestions">{[{icon:Sparkles,title:'Darle forma a una idea',text:'Ayudame a organizar una idea de proyecto. Haceme preguntas para empezar.'},{icon:Terminal,title:'Pensar en código',text:'Ayudame a entender y mejorar un fragmento de código.'},{icon:FolderOpen,title:'Explorar mis archivos',text:'Listá los archivos de mi carpeta autorizada.',agent:true}].map(s=><button key={s.title} onClick={()=>{setText(s.text);if(s.agent)setMode('agent');input.current?.focus()}}><s.icon size={19}/><strong>{s.title}</strong><span>{s.agent?'Con herramientas y permisos':'Empecemos una conversación'} ↗</span></button>)}</div><div className="welcome-bottom"><ShieldCheck size={14}/>Tus archivos solo se consultan en las carpetas que autorizaste.</div></div>:<div className="message-list">{messages.map((m,i)=><article className={'message '+m.role} key={m.id??i}><div className="message-avatar">{m.role==='assistant'?<AudioLines size={18}/>:<span>V</span>}</div><div className="message-body"><div className="message-label">{m.role==='assistant'?'Nexo':'Vos'}{m.role==='assistant'&&<small>{shortModel(m.model||config?.model||'')}</small>}</div><div className="markdown"><ReactMarkdown remarkPlugins={[remarkGfm]} components={{img:()=>null,a:({children,href})=><a href={href} target="_blank" rel="noopener noreferrer">{children}</a>}}>{m.content|| (busy&&i===messages.length-1?'…':'')}</ReactMarkdown></div>{m.status&&m.status!=='complete'&&<small className="muted">{({stopped:'Respuesta interrumpida',error:'La generación falló',limited:'Límite de iteraciones'} as Record<string,string>)[m.status]||m.status}</small>}{m.role==='assistant'&&m.content&&<button className="message-voice" aria-label="Leer respuesta con voz local" onClick={()=>speak(m.content)}><Volume2 size={14}/>Escuchar</button>}</div></article>)}{actions.map((a,i)=><details className="tool-result" key={i}><summary><Wrench size={14}/>{a.tool}<span>{a.result.error?'Error':'Completado'}</span></summary><pre>{JSON.stringify(a.result,null,2)}</pre></details>)}{notice&&<div className="notice">{notice}</div>}<div ref={bottom}/></div>}</div>
        <div className="composer-area"><div className="composer-meta"><div className="mode-switch"><button className={mode==='chat'?'selected':''} disabled={busy} onClick={()=>setMode('chat')}><MessageSquare size={13}/>Chat</button><button className={mode==='agent'?'selected':''} disabled={busy} onClick={()=>setMode('agent')}><Zap size={13}/>Agente</button></div><span className={'agent-state '+(busy?'working':'')}><span className={'dot '+(busy?'amber':'green')}/>{busy?state:mode==='agent'?'Herramientas con permisos':'Listo para conversar'}</span></div>
          <form className="composer" onSubmit={send}>{images.length>0&&<div className="attachments">{images.map((image,i)=><div key={i}><img src={image} alt={'Imagen adjunta '+(i+1)}/><button type="button" aria-label="Quitar imagen" onClick={()=>setImages(p=>p.filter((_,j)=>i!==j))}><X size={13}/></button></div>)}</div>}<textarea ref={input} value={text} onChange={e=>setText(e.target.value)} placeholder={mode==='agent'?'¿Qué querés que hagamos?':'Escribile a tu IA local…'} aria-label="Mensaje" rows={2} maxLength={16000} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send()}}}/><div className="composer-bottom"><div className="attachment-buttons"><label className={'icon-button '+(!config?.vision?'disabled':'')} title="Adjuntar imagen"><ImagePlus size={18}/><input type="file" accept="image/png,image/jpeg,image/webp" disabled={!config?.vision||busy} onChange={e=>{if(e.target.files?.[0])addImage(e.target.files[0]);e.target.value=''}} aria-label="Adjuntar imagen"/></label><button type="button" className="icon-button" title="Compartir una captura de pantalla" aria-label="Compartir captura de pantalla" disabled={!config?.vision||busy} onClick={captureScreen}><Monitor size={18}/></button><button type="button" className="icon-button" title="Abrir cámara con permiso" aria-label="Abrir cámara" disabled={!config?.vision||busy} onClick={openCamera}><Camera size={18}/></button><span className="composer-divider"/><button type="button" className={'icon-button '+(recording?'recording':'')} disabled={!config?.stt||busy||transcribing} title={config?.stt?'Dictar mensaje':'STT pendiente: ver documentación de voz'} aria-label={recording?'Detener micrófono':'Iniciar micrófono'} onClick={microphone}><Mic size={18}/></button>{recording&&<small>Escuchando…</small>}{transcribing&&<small>Transcribiendo…</small>}</div><div className="send-area"><small>Shift + Enter para una nueva línea</small>{busy?<button type="button" className="send" aria-label="Detener generación" onClick={stop}><Square size={18}/></button>:<button type="submit" className="send" disabled={!text.trim()||!online||!config} aria-label="Enviar mensaje"><ArrowUp size={20}/></button>}</div></div></form><p className="composer-footnote">La IA puede equivocarse. Revisá las acciones antes de autorizarlas.</p></div>
      </section>:<div className="page-scroll"><div className="page-content"><div className="eyebrow">TU ESPACIO DE TRABAJO</div><h1>{view==='tools'?'Herramientas':view==='system'?'Sistema':'Configuración'}</h1><p className="page-intro">{view==='tools'?'Elegí qué puede hacer tu asistente. Vos definís los límites.':view==='system'?'El estado de tu asistente, sin perder de vista lo que está pasando.':'Un asistente que trabaja a tu manera.'}</p>
      {view==='tools'&&<><div className="setting-card safety-card"><ShieldCheck/><div><strong>{config?.tools_disabled?'Todas las herramientas están apagadas':'Herramientas disponibles para el modo agente'}</strong><p>En modo chat el modelo no ejecuta herramientas.</p></div><button className="secondary" onClick={()=>saveConfig({tools_disabled:!config?.tools_disabled}).catch(fail)}>{config?.tools_disabled?'Habilitar herramientas':'Apagar todas'}</button></div><div className="tool-grid">{tools.map(tool=><div className="tool-card" key={tool.name}><div className="tool-card-top"><span className="tool-icon">{tool.group==='Terminal'?<Terminal size={21}/>:<FolderOpen size={21}/>}</span><Toggle label={'Activar '+tool.name} checked={tool.enabled} disabled={config?.tools_disabled} onChange={()=>api('/tools/'+tool.name,{method:'PUT',body:json({enabled:!tool.enabled})}).then(()=>api('/tools').then(setTools)).catch(fail)}/></div><h3>{tool.name}</h3><p>{tool.description}</p><span className={'permission '+(tool.permission==='read'?'read':'')}>{tool.permission==='read'?'Lectura · Automática':tool.permission==='always'?'Siempre pide aprobación':'Escritura · Permiso configurable'}</span></div>)}</div><div className="setting-card"><Monitor/><div><strong>Control de computadora <span className="pending">Pendiente</span></strong><p>{config?.computer.reason}</p></div><Toggle checked={false} disabled label="Control de computadora pendiente" onChange={()=>{}}/></div><div className="root-info"><FolderOpen size={17}/><div><strong>Carpetas autorizadas</strong>{config?.roots.map(r=><code key={r}>{r}</code>)}<small>Se modifican en AUTHORIZED_ROOTS, dentro de .env.</small></div></div></>}
      {view==='system'&&<><div className="system-grid">{[{label:'Backend',value:backend?'Conectado':'Sin conexión',ok:backend,icon:Globe},{label:'Ollama',value:online?'Conectado':'Desconectado',ok:online,icon:Cpu},{label:'Agente',value:system?.agent||state,ok:!busy,icon:Zap},{label:'Micrófono',value:recording?'Escuchando':config?.stt?'Apagado':'STT pendiente',ok:!!config?.stt,icon:Mic},{label:'Cámara',value:camera?'Activa con permiso':'Apagada',ok:!camera,icon:Camera},{label:'Modelo activo',value:shortModel(system?.active_model||config?.model||'—'),ok:online,icon:MessageSquare}].map(s=><div className="system-card" key={s.label}><s.icon size={19}/><span>{s.label}</span><strong><span className={'dot '+(s.ok?'green':'amber')}/>{s.value}</strong></div>)}</div><button className="secondary refresh" onClick={()=>refresh().catch(fail)}>Actualizar conexión y modelos</button><div className="section-title"><h2>Registro de acciones</h2><span>Últimos 80 eventos</span></div><div className="logs">{system?.logs?.length?system.logs.map((l:any)=><details key={l.id}><summary><span className={'log-state '+(l.state==='error'?'bad':'')}>{l.state}</span><strong>{l.tool}</strong><time>{new Date(l.created*1000).toLocaleTimeString()}</time></summary><pre>{l.detail}</pre></details>):<div className="empty-logs"><Check size={24}/><p>Todavía no hay acciones registradas.</p><small>Las llamadas a herramientas y los errores aparecerán acá.</small></div>}</div></>}
      {view==='settings'&&config&&<><div className="settings-stack"><div className="setting-card"><Zap/><div><strong>Límite del agente</strong><p>Máximo de iteraciones por mensaje (entre 1 y 12).</p></div><input aria-label="Máximo de iteraciones" type="number" min={1} max={12} value={config.max_iterations} onChange={e=>{const n=Number(e.target.value);if(n>=1&&n<=12)saveConfig({max_iterations:n}).catch(fail)}}/></div><div className="setting-card"><ShieldCheck/><div><strong>Confirmar cambios en archivos</strong><p>Ver el contenido y la ruta antes de crear o modificar archivos.</p></div><Toggle label="Confirmar cambios en archivos" checked={config.confirm_writes} onChange={()=>saveConfig({confirm_writes:!config.confirm_writes}).catch(fail)}/></div><div className="setting-card"><Volume2/><div><strong>Leer respuestas automáticamente</strong><p>Usa únicamente voces locales en español del navegador.</p></div><Toggle label="Voz automática" checked={config.auto_voice} onChange={()=>saveConfig({auto_voice:!config.auto_voice}).catch(fail)}/></div><div className="setting-card"><Mic/><div><strong>Reconocimiento de voz</strong><p>{config.stt?'Whisper local disponible. Usá el micrófono para dictar.':'Pendiente de instalar faster-whisper y un modelo local. Ver docs/voz.md.'}</p></div><span className="pending">{config.stt?'Disponible':'Pendiente'}</span></div></div><div className="section-title"><h2>Memoria persistente</h2><span>Solo lo que vos guardás</span></div><p className="muted">Estas notas se agregan al contexto de las próximas conversaciones. Podés borrarlas cuando quieras.</p><form className="memory-form" onSubmit={e=>{e.preventDefault();if(memory.trim())api('/memory',{method:'POST',body:json({content:memory})}).then(()=>{setMemory('');api('/memory').then(setMemories)}).catch(fail)}}><input aria-label="Nueva memoria" value={memory} maxLength={1000} onChange={e=>setMemory(e.target.value)} placeholder="Por ejemplo: prefiero explicaciones con ejemplos…"/><button className="secondary" disabled={!memory.trim()}>Guardar</button></form><div className="memory-list">{memories.map(m=><div key={m.id}><FileText size={17}/><span>{m.content}</span><button className="icon-button" aria-label="Eliminar memoria" onClick={()=>api('/memory/'+m.id,{method:'DELETE'}).then(()=>api('/memory').then(setMemories)).catch(fail)}><Trash2 size={16}/></button></div>)}</div><div className="remote-note"><LockKeyhole size={20}/><div><strong>Acceso remoto privado</strong><p>Preparado para Tailscale Serve. La activación es manual; consultá docs/acceso-remoto.md. Ollama permanece local.</p></div></div></>}
      </div></div>}
    </main>
    {approval&&<div className="modal-backdrop"><section className="approval-modal" role="dialog" aria-modal="true" aria-labelledby="approval-title"><div className="eyebrow"><ShieldCheck size={16}/> VOS TENÉS LA ÚLTIMA PALABRA</div><h2 id="approval-title">El agente necesita tu permiso</h2><p><strong>{approval.tool}</strong> · {approval.risk}</p>{approval.tool==='powershell'&&<div className="warning">Este comando tiene los permisos de tu usuario de Windows y puede acceder fuera de las carpetas autorizadas.</div>}<pre>{JSON.stringify(approval.arguments,null,2)}</pre><small>La aprobación vale solo para esta acción y vence en 3 minutos.</small><div className="modal-actions"><button className="secondary" onClick={()=>decide(false)}>Rechazar</button><button className="primary" onClick={()=>decide(true)}>Aprobar esta acción</button></div></section></div>}
    {camera&&<div className="modal-backdrop"><section className="camera-modal" role="dialog" aria-modal="true" aria-label="Capturar imagen de cámara"><h2>Cámara activa</h2><p>La imagen se envía al modelo únicamente cuando mandás el mensaje.</p><video ref={video} autoPlay playsInline muted/><div className="modal-actions"><button className="secondary" onClick={closeCamera}>Cerrar cámara</button><button className="primary" onClick={()=>{if(video.current)captureVideo(video.current);closeCamera()}}>Tomar foto</button></div></section></div>}
  </div>
}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);

