"""Extension boundary. Native PC input is deliberately unavailable until a
reviewed adapter implements cancellation, foreground-window checks and approvals.
Browser screen capture is available through explicit getDisplayMedia permission.
"""
from typing import Protocol

class ComputerController(Protocol):
    async def screenshot(self) -> bytes: ...
    async def move_mouse(self, x: int, y: int): ...
    async def click(self, x: int, y: int): ...
    async def type_text(self, text: str): ...
    async def press_key(self, key: str): ...
    async def open_application(self, name: str): ...
    async def switch_window(self, title: str): ...
    async def stop(self): ...

STATUS = {'available': False, 'reason': 'Pendiente: control nativo, mouse, teclado y Playwright. No se ejecutan acciones de PC.'}
