from typing import Protocol, AsyncIterator

class ChatProvider(Protocol):
    async def models(self) -> list[dict]: ...
    def stream(self, model: str, messages: list, tools: list, capabilities: list) -> AsyncIterator[dict]: ...
